[build]
builder = "NIXPACKS"
buildCommand = "NEXT_PUBLIC_MEILISEARCH_READ_API_KEY=$(node get_search_key.mjs) && yarn migrate:deploy && yarn generate && yarn build"

[deploy]
numReplicas = 2
sleepApplication = false
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10

[environments.pr.deploy]
numReplicas = 1
